name: Build and Release
# im new to workflows and actions so dont make fun of this :) im hoping i got it working now 
on:
  push:
    tags:
      - '*'  # Run on any tag push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with MSVC
        run: cl /EHsc cbmic.cpp /Fe:cbmic.exe /link user32.lib

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload exe to Release
        uses: softprops/action-gh-release@v2
        with:
          files: cbmic.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#git tag v1.0 && git push origin v1.0