name: Build and Release

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with MSVC
        run: cl /EHsc cbmic.cpp /Fe:cbmic.exe /link user32.lib

      - name: Get version or short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.sha_short }}
          name: Release ${{ env.sha_short }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload exe to Release
        uses: softprops/action-gh-release@v2
        with:
          files: cbmic.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
